theme: jekyll-theme-cayman
title: "Scaling NLP Applications to 100+ Languages"
subtitle: "A Tutorial Proposal for The Web Conference 2021"
description: "A Tutorial Proposal for The Web Conference 2021"
