theme: jekyll-theme-cayman
title: "Scaling out NLP Applications to 100+ Languages"
subtitle: "Lecture Tutorial for The Web Conference 2021|April 19-23, 2021, Ljubljana"
description: "Linjun Shou, Ming Gong, Jian Pei, Xiubo Geng, Xingjie Zhou and Daxin Jiang"
